/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world!!!!!!!!!!!3232132sdf";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        for(int i = 0; i < 10; i++) {
        	System.out.println(i);
        }
    }
}
